spring:
  application:
    name: application-action
  cloud:
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}-group


feign:
  httpclient:
    connection-timeout: 5000
    connection-timer-repeat: 5000

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:3333/eureka/




logging:
  level:
    com.example: debug

server:
  port: 7777


seata:
  enabled: true
  application-id: ${spring.application.name}-application
  tx-service-group: my_test_tx_group
  service:
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      my_test_tx_group: default
  enable-auto-data-source-proxy: false

